version: '3'
services:
  # Serviço de notificações
  notification:
    container_name: notification-service
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      - REDIS_URI=redis://redis:6379

  # Cache Redis para o serviço de notificações
  redis:
    container_name: redis-container
    image: "redis:latest"
    ports:
      - "6379:6379"

  # Monitoramento com Prometheus
  prometheus:
    container_name: prometheus-container
    image: prom/prometheus:latest
    ports:
      - "9090:9090"

  # Monitoramento com Grafana
  grafana:
    container_name: grafana-container
    image: grafana/grafana:latest
    ports:
      - "3001:3001"
