version: '3'
services:
  app:
    container_name: simplecrudjs
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://root:admin@mongo:27017
    volumes:
      - .:/usr/src/app
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    container_name: dbcontainer
    image: "mongo:4.4"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes: 
  mongodb_data:
